### ISSUE TITLE
请求提供获取uuid的思路

### ISSUE THREAD

**Issue by junnanl** [lixiang810/totoroschool-autorun#4]
龙猫跳转微信授权界面 参数uuid 该如何通过抓包获取
(已测试使用代理方式抓包 但龙猫检测vpn 无法进入 使用 frida hook 对于如何操作没有思路)
恳请作者大大指点

**Comment by lixiang810** [comment]
uuid 是随机生成的。

https://github.com/lixiang810/totoroschool-autorun/blob/main/src/controllers/generateSunRunExercisesReq.ts#L64

**Comment by lixiang810** [comment]
龙猫检测 VPN，可以用“对话框取消”这个 Xposed 插件来屏蔽。

我这个项目也不处理微信授权，而是处理微信授权以后的事情。

**Comment by junnanl** [comment]
好的 多谢大大指点
