### ISSUE TITLE
请求提供获取HTTPS请求响应数据的方法。

### ISSUE THREAD

**Issue by msj1010** [lixiang810/totoroschool-autorun#5]
博主你好，我是南京仙林某高校软件工程专业学生，也深受龙猫校园的毒害，博主应该是浦口南京信息工程大学的学生吧。我现在使用Fiddler导出证书安装到夜神模拟器上，在模拟器上使用Xposed框架绕过代理登录了龙猫校园，但是只能抓取到域名“collecter.pgyer.com”的数据，抓取到的数据请求体如下，而无法获取响应体。前段时间可以抓取到“app.xtotoro.com”的数据。请问博主是解决无法抓取响应体这个问题的呢？或者我的思路本身就有什么错误。如果方便的话，可以加个联系方式进一步交流。我的QQ：1548370262
请求体样例：
`[
    {
        "currentURL": "com.totoro.ft_home.ui.activity.run.task.MovementRecordActivity@3366e7d2",
        "token": "73923cb163380e4017f844c5516d7567",
        "deviceData": {
            "network": 4,
            "deviceID": "e246bfb6d06f9fe7b40d1d256ded18f4",
            "appname": "com.totoro.school",
            "freeDiskSpace": 63621595136,
            "isRoot": false,
            "appversion": "2.0.3",
            "brand": "Android",
            "name": "Android",
            "ostype": "Android",
            "freeRam": 1540608000,
            "isPortrait": true,
            "appversioncode": 103,
            "model": "MI 9"
        },
        "data": {
            "detail": {
                "view": 0
            },
            "message": 1024
        },
        "refererURL": "com.totoro.ft_home.ui.activity.run.task.MovementDetailsActivity@2a669c77",
        "viewPort": {
            "r": 1.5,
            "h": 1280,
            "w": 720
        },
        "sessionID": "ffff018410ef9d7e5834ce112f5148a6",
        "version": "4.2.0",
        "currentRoute": "com.totoro.ft_home.ui.activity.run.task.MovementRecordActivity",
        "type": 1024,
        "userAgent": "Mozilla\/5.0 (Linux; Android 5.1.1; MI 9 Build\/NMF26X; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/74.0.3729.136 Mobile Safari\/537.36",
        "refererRoute": "com.totoro.ft_home.ui.activity.run.task.MovementDetailsActivity",
        "messageID": "ffff018416bc7b590c0f650359f76de3",
        "clientID": "ffff016817022c88b5b3d4bbd2249d8b"
    }
]`

**Comment by lixiang810** [comment]
1. `collecter.pgyer.com` 基本可以认为是统计数据，不需要获取。（可能关系到 iOS 端的登录状态保持，未研究）
2. `app.xtotoro.com` 是 https 响应，需要安装证书，并且安装到 Android 的系统证书（`/system` 目录下）。抓取到数据后的解密方法可见 https://github.com/lixiang810/totoroschool-autorun/blob/main/src/utils/decryptRequestContent.ts
